# Generated by Django 3.2 on 2021-05-21 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='papers.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='done_by',
            field=models.ManyToManyField(related_name='done_modules', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='module',
            name='topics',
            field=models.ManyToManyField(related_name='modules', to='papers.Topic'),
        ),
        migrations.AlterField(
            model_name='module',
            name='try_by',
            field=models.ManyToManyField(related_name='try_modules', to='accounts.Profile'),
        ),
    ]
