# Generated by Django 3.2 on 2022-03-09 15:15

from django.db import migrations, models
import django.db.models.deletion
import papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0001_initial'),
        ('papers', '0002_module_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('access_to_everyone', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to=papers.models.upload_location)),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_author', to='accounts.profile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='subscribepay',
            name='module',
        ),
        migrations.AlterField(
            model_name='cache',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_cache', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='cache',
            name='object_type',
            field=models.TextField(default='lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_folders', to='accounts.profile'),
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='Page',
        ),

        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='papers.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='done_by',
            field=models.ManyToManyField(related_name='done_lessons', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topics',
            field=models.ManyToManyField(related_name='lessons', to='papers.Page'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='try_by',
            field=models.ManyToManyField(related_name='try_lessons', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='subscribepay',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_payments', to='papers.lesson'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='interested_subjects',
            field=models.ManyToManyField(default=1, related_name='interested_students', to='papers.Lesson'),
        ),
    ]
