# Generated by Django 3.2 on 2021-05-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('papers', '0002_auto_20210521_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lesson',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='subscribepay',
            old_name='lesson',
            new_name='module',
        ),
        migrations.AlterField(
            model_name='cache',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_cache', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='cache',
            name='object_type',
            field=models.TextField(default='module'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_folders', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='module',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_author', to='accounts.profile'),
        ),
    ]
