# Generated by Django 3.2 on 2022-03-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('papers', '0003_auto_20220309_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Section',
        ),
    ]
