# Generated by Django 3.2 on 2021-05-21 01:54

from django.db import migrations, models
import django.db.models.deletion
import papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20210521_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slogan', models.TextField(null=True)),
                ('shown', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to=papers.models.upload_location)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='papers.subject'),
        ),
    ]
