# Generated by Django 3.2 on 2022-03-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20220309_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='topics',
            new_name='pages',
        ),
    ]
