# Generated by Django 3.2 on 2022-03-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_auto_20220309_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='file',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
