# Generated by Django 3.2 on 2022-03-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_auto_20220310_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='topic',
            new_name='pages',
        ),
    ]
