# Generated by Django 3.2 on 2022-04-27 14:13

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, default='name', null=True)),
                ('money', models.IntegerField(default=0)),
                ('crnt_course', models.IntegerField(default=0)),
                ('is_student', models.BooleanField(default=True)),
                ('coins', models.IntegerField(default=0)),
                ('mail', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_location)),
                ('confirmed', models.BooleanField(default=True)),
                ('confirmation_code', models.CharField(default='', max_length=250)),
                ('confirmation_time', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('language', models.CharField(default='ru', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_student', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('itstype', models.CharField(max_length=25)),
                ('url', models.TextField(default='', null=True)),
                ('image_url', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_notifications', to='accounts.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
