# Generated by Django 3.2 on 2021-05-21 00:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_problem_ru', models.TextField(default='')),
                ('task_problem_kz', models.TextField(default='')),
                ('task_ans_ru', models.TextField(default='')),
                ('task_ans_kz', models.TextField(default='')),
                ('task_solve_ru', models.TextField(default='')),
                ('task_solve_kz', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=tasks.models.upload_location)),
                ('cost', models.IntegerField(default=1)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('tags', models.ManyToManyField(related_name='tasks', to='tasks.ProblemTag')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaskPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=tasks.models.upload_location)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='tasks.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solver_ans', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('solve', models.TextField(default='')),
                ('solver_correctness', models.BooleanField(default=False)),
                ('solver_try_number', models.IntegerField(default=0)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='check_tasks', to='accounts.profile')),
                ('task', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solver_checks', to='tasks.task')),
            ],
        ),
    ]
